### ISSUE TITLE
Error when fetching Security Material

### ISSUE THREAD

**Issue by Q4IT** [codebude/cpi-dashboard#1]
GroovyScript error in the processing step 'Parse sec mat and get passwords' after hitting the 'Load security material' button:

**Error Details**
```
javax.script.ScriptException: java.lang.Exception: groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.lang.String#<init>.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
[class java.lang.String]
[class [C]
[class [B]@ line 37 in secMatGetPasswords.groovy, cause: groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.lang.String#<init>.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
[class java.lang.String]
[class [C]
[class [B]
```

The message payload contains a lot of null values:
"User":"none","Password":null,"

**Comment by codebude** [comment]
Hi @Q4IT ,

thanks for your input. How can I reproduce thus entries with null values (`"User":"none","Password":null"`)? Is it just security material from CPI which has no user and password maintained?

Regards,
Raffael

**Comment by Q4IT** [comment]
Hi Raffael,

All security material has **Password: null** in the response message however, they are not empty in fact.

Regards, 
Rik

**Comment by codebude** [comment]
Hi @Q4IT ,

I could partly reproduce it. But before I bring it in the next release and it doesn't work for you, I kindly ask you to try the patch before. Could you please replace line 36-38 in the "" script:
``` Java
        if (credential != null){
            pw = new String(credential.getPassword())            
        }
```
with the following
``` Java
        if (credential != null){
            def pwTmp = credential.getPassword()
            if (pwTmp != null && pwTmp.size() > 0){
                pw = new String(credential.getPassword())
            } else {
                pw = ""
            }
        }
```
and try it again?

**Comment by Q4IT** [comment]
Hi Raffael,

Thank you for your quick response, your patch did the trick and everything is now working correctly! You can implement it in the next release :)

Regards,
Rik

**Comment by codebude** [comment]
Thanks for the feedback. I plan to release the next version during this week. By the way - you pointed me to another bug. I assume you picked the error code from your browser's developer tools, but usually it should show up in the front end. This will work again also from the next release. :-)
