### ISSUE TITLE
Mixed Content Error on XMLHttpRequest: Switch to HTTPS Required

### ISSUE THREAD

**Issue by eklass** [codebude/cpi-dashboard#7]
When accessing the dashboard over HTTPS, a Mixed Content error occurs due to a request being sent to an insecure HTTP URL. The browser blocks this request, causing the page to malfunction.

Steps to Reproduce:

Open the page at https://cpiurl/dashboard/.
Check the browser console (e.g., using Developer Tools).
The following error appears:
Mixed Content: The page at 'https://cpiurl/dashboard/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://cpiurl//status'. This request has been blocked; the content must be served over HTTPS.
Expected Behavior:
All requests should be sent over HTTPS to avoid Mixed Content errors and ensure the security of the page.

Proposed Solution:

Update all HTTP URLs in the relevant scripts, configurations, and Base64-encoded content to HTTPS.
Ensure that the server serves the necessary resources over HTTPS.

Environment:
Browser: [e.g., Chrome, Firefox]
URL: https://cpiurl/dashboard/

Additional Information:
If there are HTTP URLs embedded in Base64-encoded content, these should also be updated to HTTPS.
Also there seems some invalid urls mapped when accessing the dashboard (diffutils, status and scheduler has double slash in the url)

![Realcore-Error](https://github.com/user-attachments/assets/aa6efa40-1acb-4d01-a657-1644c3f09a19)

**Comment by eklass** [comment]
I fixed it by editing deliverStaticContent.groovy by adding these two lines:

    //Parse static content
    staticContent = new String(staticContent.decodeBase64(), "UTF-16LE")
    def baseUrl = "${message.getHeaders().get('CamelHttpUrl').replace('/dashboard','')}".toString()
    // Fix url below
    baseUrl = baseUrl.replaceAll(/\/$/, '')
    baseUrl = baseUrl.replaceFirst("^http:", "https:")

This snipped removes the last slash at the end and replace the baseUrl http with https.
Maybe unter NEO "CamelHttpUrl" contained the necessary https url. Under CF we just get http.

**Comment by codebude** [comment]
Hi @eklass ,

do you mind sending in a PR with your bugfix?
